### ISSUE TITLE
pypi and github versions differ

### ISSUE THREAD

**Issue by makefu** [adc4392/python-cloudatcost#10]
on pypi the version 0.5.2 is available, the repo contains 0.5.1

https://pypi.python.org/pypi/cacpy/0.5.2

**Comment by aculler** [comment]
Hmmm. That's super weird. I'll look into that. Thanks for the callout.

**Comment by makefu** [comment]
any updates about that one?

**Comment by aculler** [comment]
Hey @makefu 

I looked into this a little bit and the code that pip installs is exactly the same as the current code in the repo. It looks as though at some point the version numbers got out of sync, but the code is the same. I haven't had a chance to get them sync'd up, but will get to it at some point in the (hopefully) near future.

**Comment by makefu** [comment]
ok, thanks for investigating :)
i finished the code for the cac panel but at first i kept it out of your api repo,
you can check it out at https://github.com/makefu/cacpanel
