### ISSUE TITLE
PIP

### ISSUE THREAD

**Issue by aculler** [adc4392/python-cloudatcost#2]
Shape the code up to meet any requirements (need to research) related to submitting to pip. I want to make it so that people can easily install this lib, especially if it's a dependency for another script.

**Comment by Matt3o12** [comment]
+1

**Comment by ferrix** [comment]
Just go ahead already. For your own sake, running versioneer.py would bind the version to git tags but otherwise you are ready.

**Comment by aculler** [comment]
Sorry for this taking so damn long to accomplish. I've never submitted anything to PyPi before, so I just needed to buckle down and research how. I'm happy to announce that it's now available on PyPi!

https://pypi.python.org/pypi/cacpy
